import { Document, Page, Text, View } from "@react-pdf/renderer";
import { DocumentFooter, DocumentHeader } from "@/lib/pdf/DocumentHeader";
import { pdfStyles } from "@/lib/pdf/styles";
import { formatMoney } from "@/lib/pdf/company";

interface InvoiceItemRow {
  material: { sku: string; name: string };
  quantity: string;
  unitPrice: string;
}

interface InvoiceForPdf {
  invoiceNo: string;
  invoiceDate: string;
  totalAmount: string;
  taxAmount: string;
  customer: { name: string; phone: string | null; address: string | null };
  salesOrder: { orderNo: string } | null;
  items: InvoiceItemRow[];
  payments: { amount: string }[];
}

export function invoiceNumber(invoice: { invoiceNo: string }) {
  return invoice.invoiceNo;
}

function qty(value: string) {
  return Number(value).toLocaleString("en-LK", { maximumFractionDigits: 3 });
}

export function InvoiceDocument({ invoice }: { invoice: InvoiceForPdf }) {
  const lineTotal = (item: InvoiceItemRow) => Number(item.quantity) * Number(item.unitPrice);
  const subtotal = invoice.items.reduce((sum, item) => sum + lineTotal(item), 0);
  const paid = invoice.payments.reduce((sum, p) => sum + Number(p.amount), 0);
  const balanceDue = Number(invoice.totalAmount) - paid;

  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        <DocumentHeader
          title="Sales Invoice"
          documentNo={invoiceNumber(invoice)}
          date={new Date(invoice.invoiceDate).toLocaleDateString("en-LK")}
        />

        <View style={[pdfStyles.section, pdfStyles.sectionRow]}>
          <View style={pdfStyles.sectionBlock}>
            <Text style={pdfStyles.label}>Bill To</Text>
            <Text style={pdfStyles.value}>{invoice.customer.name}</Text>
            <Text style={pdfStyles.value}>{invoice.customer.address ?? "—"}</Text>
            <Text style={pdfStyles.value}>{invoice.customer.phone ?? "—"}</Text>
          </View>
          <View style={pdfStyles.sectionBlock}>
            <Text style={pdfStyles.label}>From Sales Order</Text>
            <Text style={pdfStyles.value}>{invoice.salesOrder?.orderNo ?? "Standalone invoice"}</Text>
          </View>
        </View>

        <View style={pdfStyles.table}>
          <View style={pdfStyles.tableHeaderRow}>
            <Text style={[pdfStyles.th, { width: "10%" }]}>SKU</Text>
            <Text style={[pdfStyles.th, { width: "42%" }]}>Product</Text>
            <Text style={[pdfStyles.th, { width: "16%", textAlign: "right" }]}>Qty</Text>
            <Text style={[pdfStyles.th, { width: "16%", textAlign: "right" }]}>Unit Price</Text>
            <Text style={[pdfStyles.th, { width: "16%", textAlign: "right", borderRight: "none" }]}>Line Total</Text>
          </View>
          {invoice.items.map((item, index) => (
            <View style={pdfStyles.tableRow} key={index}>
              <Text style={[pdfStyles.td, { width: "10%" }]}>{item.material.sku}</Text>
              <Text style={[pdfStyles.td, { width: "42%" }]}>{item.material.name}</Text>
              <Text style={[pdfStyles.td, { width: "16%", textAlign: "right" }]}>{qty(item.quantity)}</Text>
              <Text style={[pdfStyles.td, { width: "16%", textAlign: "right" }]}>{formatMoney(item.unitPrice)}</Text>
              <Text style={[pdfStyles.td, { width: "16%", textAlign: "right", borderRight: "none" }]}>
                {formatMoney(lineTotal(item))}
              </Text>
            </View>
          ))}
        </View>

        <View style={pdfStyles.totalsBlock}>
          <View style={pdfStyles.totalsRow}>
            <Text style={pdfStyles.totalsLabel}>Subtotal</Text>
            <Text style={pdfStyles.totalsValue}>{formatMoney(subtotal)}</Text>
          </View>
          <View style={pdfStyles.totalsRow}>
            <Text style={pdfStyles.totalsLabel}>Tax</Text>
            <Text style={pdfStyles.totalsValue}>{formatMoney(invoice.taxAmount)}</Text>
          </View>
          <View style={pdfStyles.totalsRow}>
            <Text style={pdfStyles.totalsLabel}>Total</Text>
            <Text style={pdfStyles.totalsValue}>{formatMoney(invoice.totalAmount)}</Text>
          </View>
          <View style={pdfStyles.totalsRow}>
            <Text style={pdfStyles.totalsLabel}>Paid</Text>
            <Text style={pdfStyles.totalsValue}>{formatMoney(paid)}</Text>
          </View>
          <View style={pdfStyles.totalsRow}>
            <Text style={pdfStyles.totalsLabel}>Balance Due</Text>
            <Text style={pdfStyles.balanceDue}>{formatMoney(balanceDue)}</Text>
          </View>
        </View>

        <View style={pdfStyles.signatureRow}>
          <Text style={pdfStyles.signatureBlock}>Customer Signature</Text>
          <Text style={pdfStyles.signatureBlock}>Authorized Signature</Text>
        </View>

        <DocumentFooter note="Generated by Nestraa Management System" />
      </Page>
    </Document>
  );
}
