import { Document, Page, Text, View } from "@react-pdf/renderer";
import { DocumentFooter, DocumentHeader } from "@/lib/pdf/DocumentHeader";
import { pdfStyles } from "@/lib/pdf/styles";
import { COMPANY, formatAmount, formatMoney } from "@/lib/pdf/company";

interface LedgerEntryRow {
  transactionDate: string;
  transactionType: "delivery" | "payment" | "return";
  description: string | null;
  debit: string;
  credit: string;
  runningBalance: string;
}

const typeLabels: Record<LedgerEntryRow["transactionType"], string> = {
  delivery: "Delivery",
  payment: "Payment",
  return: "Return",
};

export function StatementDocument({
  retailer,
  entries,
  outstandingBalance,
}: {
  retailer: { name: string; retailerCode: string; phone: string | null; address: string | null };
  entries: LedgerEntryRow[];
  outstandingBalance: string;
}) {
  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        <DocumentHeader
          title="Retailer Statement"
          documentNo={retailer.retailerCode}
          date={new Date().toLocaleDateString("en-LK")}
        />

        <View style={pdfStyles.section}>
          <Text style={pdfStyles.label}>Retailer</Text>
          <Text style={pdfStyles.value}>{retailer.name}</Text>
          <Text style={pdfStyles.value}>{retailer.address ?? "—"}</Text>
          <Text style={pdfStyles.value}>{retailer.phone ?? "—"}</Text>
        </View>

        <Text style={pdfStyles.label}>Amounts in {COMPANY.currency}</Text>
        <View style={pdfStyles.table}>
          <View style={pdfStyles.tableHeaderRow}>
            <Text style={[pdfStyles.th, { width: "13%" }]}>Date</Text>
            <Text style={[pdfStyles.th, { width: "13%" }]}>Type</Text>
            <Text style={[pdfStyles.th, { width: "38%" }]}>Description</Text>
            <Text style={[pdfStyles.th, { width: "12%", textAlign: "right" }]}>Debit</Text>
            <Text style={[pdfStyles.th, { width: "12%", textAlign: "right" }]}>Credit</Text>
            <Text style={[pdfStyles.th, { width: "12%", textAlign: "right", borderRight: "none" }]}>Balance</Text>
          </View>
          {entries.length === 0 ? (
            <View style={pdfStyles.tableRow}>
              <Text style={[pdfStyles.td, { width: "100%", borderRight: "none" }]}>No transactions yet.</Text>
            </View>
          ) : (
            entries.map((entry, index) => (
              <View style={pdfStyles.tableRow} key={index}>
                <Text style={[pdfStyles.td, { width: "13%" }]}>{new Date(entry.transactionDate).toLocaleDateString("en-LK")}</Text>
                <Text style={[pdfStyles.td, { width: "13%" }]}>{typeLabels[entry.transactionType]}</Text>
                <Text style={[pdfStyles.td, { width: "38%" }]}>{entry.description ?? "—"}</Text>
                <Text style={[pdfStyles.td, { width: "12%", textAlign: "right" }]}>
                  {Number(entry.debit) > 0 ? formatAmount(entry.debit) : "—"}
                </Text>
                <Text style={[pdfStyles.td, { width: "12%", textAlign: "right" }]}>
                  {Number(entry.credit) > 0 ? formatAmount(entry.credit) : "—"}
                </Text>
                <Text style={[pdfStyles.td, { width: "12%", textAlign: "right", borderRight: "none" }]}>
                  {formatAmount(entry.runningBalance)}
                </Text>
              </View>
            ))
          )}
        </View>

        <View style={pdfStyles.totalsBlock}>
          <View style={pdfStyles.totalsRow}>
            <Text style={pdfStyles.totalsLabel}>Outstanding Balance</Text>
            <Text style={pdfStyles.balanceDue}>{formatMoney(outstandingBalance)}</Text>
          </View>
        </View>

        <DocumentFooter note="Generated by Nestraa Management System" />
      </Page>
    </Document>
  );
}
