import { Document, Page, Text, View } from "@react-pdf/renderer";
import { DocumentFooter, DocumentHeader } from "@/lib/pdf/DocumentHeader";
import { pdfStyles } from "@/lib/pdf/styles";
import { formatMoney } from "@/lib/pdf/company";

interface SupplierPaymentForPdf {
  id: string;
  paymentDate: string;
  amount: string;
  paymentMethod: string;
  referenceNumber: string | null;
  notes: string | null;
  supplier: { name: string; phone: string | null; address: string | null };
  invoice: { invoiceNo: string } | null;
  recorder: { fullName: string } | null;
}

export function voucherNumber(payment: { id: string }) {
  return `PV-${payment.id.slice(0, 8).toUpperCase()}`;
}

export function SupplierPaymentVoucherDocument({ payment }: { payment: SupplierPaymentForPdf }) {
  return (
    <Document>
      <Page size="A4" style={pdfStyles.page}>
        <DocumentHeader
          title="Payment Voucher"
          documentNo={voucherNumber(payment)}
          date={new Date(payment.paymentDate).toLocaleDateString("en-LK")}
        />

        <View style={[pdfStyles.section, pdfStyles.sectionRow]}>
          <View style={pdfStyles.sectionBlock}>
            <Text style={pdfStyles.label}>Paid To</Text>
            <Text style={pdfStyles.value}>{payment.supplier.name}</Text>
            <Text style={pdfStyles.value}>{payment.supplier.address ?? "—"}</Text>
            <Text style={pdfStyles.value}>{payment.supplier.phone ?? "—"}</Text>
          </View>
          <View style={pdfStyles.sectionBlock}>
            <Text style={pdfStyles.label}>Against Invoice</Text>
            <Text style={pdfStyles.value}>{payment.invoice?.invoiceNo ?? "General payment"}</Text>
            <Text style={pdfStyles.label}>Recorded By</Text>
            <Text style={pdfStyles.value}>{payment.recorder?.fullName ?? "—"}</Text>
          </View>
        </View>

        <View style={pdfStyles.table}>
          <View style={pdfStyles.tableHeaderRow}>
            <Text style={[pdfStyles.th, { width: "34%" }]}>Method</Text>
            <Text style={[pdfStyles.th, { width: "33%" }]}>Reference #</Text>
            <Text style={[pdfStyles.th, { width: "33%", textAlign: "right", borderRight: "none" }]}>Amount</Text>
          </View>
          <View style={pdfStyles.tableRow}>
            <Text style={[pdfStyles.td, { width: "34%" }]}>{payment.paymentMethod.replace(/_/g, " ")}</Text>
            <Text style={[pdfStyles.td, { width: "33%" }]}>{payment.referenceNumber ?? "—"}</Text>
            <Text style={[pdfStyles.td, { width: "33%", textAlign: "right", borderRight: "none" }]}>
              {formatMoney(payment.amount)}
            </Text>
          </View>
        </View>

        {payment.notes && (
          <View style={pdfStyles.section}>
            <Text style={pdfStyles.label}>Notes</Text>
            <Text style={pdfStyles.value}>{payment.notes}</Text>
          </View>
        )}

        <View style={pdfStyles.totalsBlock}>
          <View style={pdfStyles.totalsRow}>
            <Text style={pdfStyles.totalsLabel}>Amount Paid</Text>
            <Text style={pdfStyles.balanceDue}>{formatMoney(payment.amount)}</Text>
          </View>
        </View>

        <View style={pdfStyles.signatureRow}>
          <Text style={pdfStyles.signatureBlock}>Prepared By</Text>
          <Text style={pdfStyles.signatureBlock}>Authorized Signature</Text>
        </View>

        <DocumentFooter note="Generated by Nestraa Management System" />
      </Page>
    </Document>
  );
}
